Installer:
- Architecture: x64
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/kate/release-24.12/windows/kate-release_24.12-9097-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 6ECAD7ABA288E8507F6B5DE3BA28F3B709324E8293AA4A7D474D2A68EE589AFB
Locale: []
Version: 24.12-9097
RealVersion: 24.12.2
