Installer:
- Architecture: x64
  InstallerUrl: https://cdn.kde.org/ci-builds/utilities/filelight/release-24.12/windows/filelight-release_24.12-1630-windows-cl-msvc2022-x86_64.exe
  InstallerSha256: 87F05BF6B06EFCA5565D03A0C40F8D58726B97B329463EB07F31D58107AB3ABD
Locale: []
Version: 24.12-1630
RealVersion: 24.12.2
