Installer:
- Architecture: x64
  InstallerUrl: https://github.com/oven-sh/bun/releases/download/bun-v1.2.4/bun-windows-x64.zip
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    To install Bun v1.2.4
    curl -fsSL https://bun.sh/install | bash
    # or you can use npm
    # npm install -g bun
    Windows:
    powershell -c "irm bun.sh/install.ps1|iex"
    To upgrade to Bun v1.2.4:
    bun upgrade
    Read Bun v1.2.4's release notes on Bun's blog
    Thanks to 17 contributors!
    - @190n
    - @cirospaciari
    - @daniellionel01
    - @donisaac
    - @dy0gu
    - @dylan-conway
    - @gbbelloponce
    - @heimskr
    - @jakeboone02
    - @jarred-sumner
    - @nektro
    - @paperclover
    - @pfgithub
    - @pranav2612000
    - @riskymh
    - @shulaoda
    - @versecafe
- Key: ReleaseNotesUrl
  Value: https://github.com/oven-sh/bun/releases/tag/bun-v1.2.4
Version: 1.2.4
ReleaseTime: 2025-02-26T10:17:09.0000000Z
