Installer:
- Architecture: x86
  InstallerUrl: https://github.com/Bforartists/Bforartists/releases/download/v4.3.3/Install_Bforartists4_433.exe
Locale:
- Locale: en-US
  Key: ReleaseNotes
  Value: |-
    Hotfix for Colored Collection Rows Release

    This is a hotfix and commulative stability release with 7 show-stopper bug fixes, including the missing Last Operator panel, HIP support, and theme saving.
    This is part of an exciting release with all the latest from Blender 4.3 and 4.4 to the date - with a chunk of 176 pieces of love from us this cycle.
    What's new with the 4.3 series!
    Additionally includes:
    - Horizontal walk navigation lock
    - Smarter Smart delete in Mesh Edit mode (removes isolated geometry now)
    - New Colored Collection Rows highlights
    - New Grease Pencil Nodegroups in the Default Library
    - New Silhouette toggle for the 3D View with the Power User Tools
    - New Asset Shelf category defaults and tag filtering, with additional thumbnail quick size buttons
    - Refined Grease Pencil 3 interface and UX
    - General maintenance, details, tooltips and refinement to everything new coming in from Blender
    Included new features from Blender are:
    - New editing of Text Strips in the Preview of the Sequencer editor
    - New Geometry Nodes: Find in String, Collection and Object Input
    - New Geometry Nodes "For Each" zone, Grease Pencil nodes, and much more
    - New method to swap and resize areas
    - New Metal BSDF
    - Videos can now render in 10bit
    - New Animation Slots to assign multiple objects to the same Action Clip
    - And much more
    - And much more.
    Downloads available from both Github, the official Website, Windows store and Blender Launcher v2
    📥 Download Free
    🌍 Official Website
    🪟 Windows App
    🧡 Blender Launcher
    📝 Release Notes
    https://www.bforartists.de/release-notes/
    🧰 Source Code
    https://github.com/Bforartists/Bforartists
    Splashscreen is kindly provided by Ethan Avila, an honorable runner up up of the last Splashscreen competition hosted in the Discord server.
    Thanks again for all your artwork, feedback and love! And a very special thanks to the community and developers for working this project.
    Draise, Reiner, Blenux (Juso), Eyad, Znight (Trung Pham), Quackers, Sean and all you arty supporters
    What's Changed
    Bforartists 4.3.3
    7 Tasks
- Key: ReleaseNotesUrl
  Value: https://github.com/Bforartists/Bforartists/releases/tag/v4.3.3
Version: v4.3.3
ReleaseTime: 2025-02-15T20:48:22.0000000Z
